apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-demo   
  template:
    metadata:
      labels:
        app: html-demo 
    spec:
      containers:     
      - name: html-demo-container
        image: nginx:alpine  # Using standard nginx to serve the injected file
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: html-content
---
apiVersion: v1
kind: Service
metadata:
  name: html-demo-service
spec:
  selector:
    app: html-demo
  ports:               
    - protocol: TCP
      port: 800
      nodeport: 3671
      targetPort: 80
  type: LoadBalancer
